name: CI - Test and Build

on:
  push:
    branches:
      - dev
      - prod

jobs:
  test-api:
    name: Run API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.1
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run API tests with pytest
        run: pytest tests/test_api.py

  test-model-metrics:
    name: Run Model Metric Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Model Metric tests with pytest
        run: pytest tests/test_metrics.py

  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest

    needs: [test-api, test-model-metrics] 

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the Docker image
        run: |
          docker build -t salary-predictor-app:latest .
      
      - name: List Docker images
        run: docker images